"""Pytest configuration for agent-os tests.

Excludes tests that depend on unimplemented modules (ops, governance, audit).
These will be re-enabled as modules are implemented.
"""

collect_ignore = [
    "test_action_fingerprint.py",
    "test_action_queue.py",
    "test_approval_decision_api.py",
    "test_approval_decision_apply.py",
    "test_approval_decision_formatter.py",
    "test_approval_decision_reader.py",
    "test_approval_decision_store.py",
    "test_approval_decision_view.py",
    "test_approval_facade.py",
    "test_approval_ops_api.py",
    "test_approval_queue_api.py",
    "test_approval_queue_formatter.py",
    "test_approval_queue_mutation.py",
    "test_approval_queue_reader.py",
    "test_approval_queue_service.py",
    "test_approval_queue_store.py",
    "test_approval_queue_view.py",
    "test_approval_status_view.py",
    "test_approval_validation.py",
    "test_audit_operational_report.py",
    "test_controlled_scheduler.py",
    "test_cooldown_filter.py",
    "test_cooldown_policy.py",
    "test_cooldown_store.py",
    "test_decision_api.py",
    "test_end_to_end_flow.py",
    "test_governance_operating_policy.py",
    "test_health_evaluator.py",
    "test_health_snapshot.py",
    "test_health_store.py",
    "test_hygiene_recommendations.py",
    "test_improvement_policy.py",
    "test_learning_memory.py",
    "test_manual_ops.py",
    "test_policy.py",
    "test_recovery_behavior.py",
    "test_run_approval_argv.py",
    "test_run_approval_command.py",
    "test_run_approval_ops.py",
    "test_run_self_operation_cycle.py",
    "test_session_hygiene.py",
]
