"""MISO Obsidian export — Export mission history to Obsidian vault"""

from __future__ import annotations
import argparse
import json
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from miso.dashboard import load_all_missions, filter_missions, get_today_range, get_week_range
from miso.formatter import STATE_LABELS, STATUS_ICONS


# Obsidian vault path
OBSIDIAN_VAULT = Path("/mnt/c/Users/milky/Documents/OpenClaw-Obsidian/openclaw")
MISO_DIR = OBSIDIAN_VAULT / "20_MISO"
MISO_DIR.mkdir(parents=True, exist_ok=True)


def get_week_number(date: datetime) -> int:
    """Get ISO week number"""
    return date.isocalendar()[1]


def format_duration_minutes(minutes: int) -> str:
    """Format duration as Xh Ym"""
    hours = minutes // 60
    mins = minutes % 60
    if hours > 0 and mins > 0:
        return f"{hours}h {mins}m"
    elif hours > 0:
        return f"{hours}h"
    else:
        return f"{mins}m"


def calculate_elapsed_minutes(mission: Dict[str, Any]) -> int:
    """Calculate elapsed minutes for a mission"""
    created_str = mission.get("created_at")
    if not created_str:
        return 0

    # Use completed_at if available, otherwise use updated_at
    completed_str = mission.get("completed_at")
    if completed_str:
        end_time = datetime.fromisoformat(completed_str.replace("Z", "+00:00"))
    else:
        updated_str = mission.get("updated_at", created_str)
        end_time = datetime.fromisoformat(updated_str.replace("Z", "+00:00"))

    start_time = datetime.fromisoformat(created_str.replace("Z", "+00:00"))
    delta = end_time - start_time
    return int(delta.total_seconds() / 60)


def count_by_state(missions: List[Dict[str, Any]]) -> Dict[str, int]:
    """Count missions by state"""
    counts: Dict[str, int] = {}
    for m in missions:
        state = m.get("state", "INIT")
        counts[state] = counts.get(state, 0) + 1
    return counts


def format_daily_report(
    missions: List[Dict[str, Any]],
    date: datetime,
) -> str:
    """Generate daily report markdown"""
    date_str = date.strftime("%Y-%m-%d")
    date_display = date.strftime("%Y/%m/%d (%a)")

    # Count stats
    total = len(missions)
    completed = sum(1 for m in missions if m.get("state") == "COMPLETE")
    error = sum(1 for m in missions if m.get("state") == "ERROR")

    # Calculate success rate
    success_rate = 0
    if completed + error > 0:
        success_rate = (completed / (completed + error)) * 100

    # Sort by state (COMPLETE first, then others)
    def sort_key(m: Dict[str, Any]) -> int:
        state = m.get("state", "")
        if state == "COMPLETE":
            return 0
        elif state == "ERROR":
            return 2
        else:
            return 1

    missions.sort(key=sort_key)

    lines = [
        f"# MISO Daily Report - {date_str}",
        "",
        f"**Date:** {date_display}",
        "",
        "## Summary",
        "",
        "| 項目 | 件数 |",
        "|------|------|",
        f"| Total | {total} |",
        f"| Complete | {completed} ✅ |",
        f"| Error | {error} ❌ |",
        f"| Success Rate | {success_rate:.1f}% |",
        "",
        "## Missions",
        "",
    ]

    for m in missions:
        mission_name = m.get("mission_name", "不明")
        mission_id = m.get("mission_id", "N/A")
        state = m.get("state", "INIT")
        goal = m.get("goal", "")
        elapsed = calculate_elapsed_minutes(m)
        duration = format_duration_minutes(elapsed)

        # Count completed agents
        agents = m.get("agents", [])
        total_agents = len(agents)
        done_agents = sum(1 for a in agents if a.get("status") == "COMPLETE")

        state_label = STATE_LABELS.get(state, state)
        icon = STATUS_ICONS.get(state, "⏳")

        lines.append(f"### {icon} {mission_name}")
        lines.append(f"- **ID:** `{mission_id}`")
        lines.append(f"- **State:** {state_label}")
        lines.append(f"- **Duration:** {duration}")
        lines.append(f"- **Goal:** {goal}")
        lines.append(f"- **Agents:** {done_agents}/{total_agents} complete")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by MISO 🌸*")

    return "\n".join(lines)


def format_weekly_report(
    missions: List[Dict[str, Any]],
    week_start: datetime,
    week_end: datetime,
) -> str:
    """Generate weekly report markdown"""
    week_number = get_week_number(week_start)
    year = week_start.year
    week_start_str = week_start.strftime("%Y-%m-%d")
    week_end_str = (week_end - timedelta(days=1)).strftime("%Y-%m-%d")

    # Count stats
    total = len(missions)
    completed = sum(1 for m in missions if m.get("state") == "COMPLETE")
    error = sum(1 for m in missions if m.get("state") == "ERROR")
    running = sum(1 for m in missions if m.get("state") in ("RUNNING", "PARTIAL", "RETRYING"))
    awaiting = sum(1 for m in missions if m.get("state") == "AWAITING_APPROVAL")

    # Calculate success rate
    success_rate = 0
    if completed + error > 0:
        success_rate = (completed / (completed + error)) * 100

    # Average completion time
    completed_missions = [m for m in missions if m.get("state") == "COMPLETE"]
    avg_time = 0
    if completed_missions:
        total_time = sum(calculate_elapsed_minutes(m) for m in completed_missions)
        avg_time = total_time / len(completed_missions)

    lines = [
        f"# MISO Weekly Report - {year}-W{week_number}",
        "",
        f"**Period:** {week_start_str} to {week_end_str}",
        "",
        "## Summary",
        "",
        "| 項目 | 件数 |",
        "|------|------|",
        f"| Total | {total} |",
        f"| Complete | {completed} ✅ |",
        f"| Error | {error} ❌ |",
        f"| Running | {running} 🔥 |",
        f"| Awaiting Approval | {awaiting} 👀 |",
        f"| Success Rate | {success_rate:.1f}% |",
        f"| Avg Completion Time | {format_duration_minutes(int(avg_time))} |",
        "",
        "## Daily Breakdown",
        "",
    ]

    # Count by day
    day_counts: Dict[str, Dict[str, int]] = {}
    for m in missions:
        created_str = m.get("created_at")
        if not created_str:
            continue
        try:
            created = datetime.fromisoformat(created_str.replace("Z", "+00:00"))
            date_key = created.strftime("%Y-%m-%d")
            if date_key not in day_counts:
                day_counts[date_key] = {"total": 0, "complete": 0, "error": 0}
            day_counts[date_key]["total"] += 1
            if m.get("state") == "COMPLETE":
                day_counts[date_key]["complete"] += 1
            elif m.get("state") == "ERROR":
                day_counts[date_key]["error"] += 1
        except Exception:
            continue

    # Sort by date
    for date_key in sorted(day_counts.keys()):
        counts = day_counts[date_key]
        date_display = datetime.fromisoformat(date_key).strftime("%m/%d (%a)")
        lines.append(f"### {date_display}")
        lines.append(f"- Total: {counts['total']} | Complete: {counts['complete']} ✅ | Error: {counts['error']} ❌")
        lines.append("")

    # List all missions
    lines.append("## All Missions")
    lines.append("")

    for m in missions:
        mission_name = m.get("mission_name", "不明")
        mission_id = m.get("mission_id", "N/A")
        state = m.get("state", "INIT")
        created_str = m.get("created_at", "")

        state_label = STATE_LABELS.get(state, state)
        icon = STATUS_ICONS.get(state, "⏳")

        # Format created date
        created_display = ""
        if created_str:
            try:
                created = datetime.fromisoformat(created_str.replace("Z", "+00:00"))
                created_display = created.strftime("%m/%d %H:%M")
            except Exception:
                pass

        lines.append(f"### {icon} {mission_name}")
        lines.append(f"- **ID:** `{mission_id}`")
        lines.append(f"- **State:** {state_label}")
        lines.append(f"- **Created:** {created_display}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by MISO 🌸*")

    return "\n".join(lines)


def export_daily_report(date: Optional[datetime] = None) -> Dict[str, Any]:
    """Export daily report to Obsidian"""
    if date is None:
        date = datetime.now(timezone.utc)

    date_str = date.strftime("%Y-%m-%d")
    filename = f"MISO-Daily-{date_str}.md"
    filepath = MISO_DIR / filename

    # Get missions for the day
    start, end = get_day_range(date)
    all_missions = load_all_missions()
    day_missions = filter_missions(all_missions, start, end)

    # Generate and save report
    content = format_daily_report(day_missions, date)
    filepath.write_text(content, encoding="utf-8")

    return {
        "ok": True,
        "path": str(filepath),
        "missions": len(day_missions),
        "date": date_str,
    }


def export_weekly_report(date: Optional[datetime] = None) -> Dict[str, Any]:
    """Export weekly report to Obsidian"""
    if date is None:
        date = datetime.now(timezone.utc)

    # Get week range
    week_start, week_end = get_week_range()

    week_number = get_week_number(week_start)
    year = week_start.year
    filename = f"MISO-Weekly-{year}-W{week_number}.md"
    filepath = MISO_DIR / filename

    # Get missions for the week
    all_missions = load_all_missions()
    week_missions = filter_missions(all_missions, week_start, week_end)

    # Generate and save report
    content = format_weekly_report(week_missions, week_start, week_end)
    filepath.write_text(content, encoding="utf-8")

    return {
        "ok": True,
        "path": str(filepath),
        "missions": len(week_missions),
        "week": f"{year}-W{week_number}",
    }


def get_day_range(date: datetime) -> tuple[datetime, datetime]:
    """Get UTC range for a specific date"""
    start = date.replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=timezone.utc)
    end = start + timedelta(days=1)
    return start, end


def main():
    parser = argparse.ArgumentParser(description="MISO Obsidian Export")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # daily command
    daily_parser = subparsers.add_parser("daily", help="Export daily report")
    daily_parser.add_argument(
        "--date",
        help="Target date (YYYY-MM-DD, default: today)",
    )

    # weekly command
    weekly_parser = subparsers.add_parser("weekly", help="Export weekly report")

    args = parser.parse_args()

    # Parse date if provided
    target_date = None
    if args.command == "daily" and args.date:
        try:
            target_date = datetime.fromisoformat(args.date).replace(tzinfo=timezone.utc)
        except ValueError:
            print(json.dumps({"ok": False, "error": "Invalid date format. Use YYYY-MM-DD"}, ensure_ascii=False))
            sys.exit(1)

    if args.command == "daily":
        result = export_daily_report(target_date)
        print(json.dumps(result, ensure_ascii=False, indent=2))
    elif args.command == "weekly":
        result = export_weekly_report()
        print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
